import { Box, Center, Heading, Text } from '@chakra-ui/react'
import Head from 'next/head'
import React from 'react'
import ContactForm from '../../components/contactForm'
import ContactInfo from '../../components/contactInfo'
import Footer from '../../components/footer'
import Header from '../../components/header'

const ContactPage = () => {
  return (
    <>
      <Head>
        <title>Unamar Comércio - Contato</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main" minH="100vh" maxW="100vw" display="flex" flexDirection="column" alignItems="center">
        <Header />
        <Box flex={1} display='flex' flexDirection='column' alignItems='center' justifyContent='center'>
          <Box display='flex' flexDirection='column' alignItems='center' justifyContent='center' mt={2} pb={2}>
            <Heading >Fale Conosco!</Heading>
            <Text textAlign='center' layerStyle="description">Entre em contato, dê sugestões, adicione seu negócio, anuncie e mais. Ficaremos felizes em receber sua mensagem.</Text>
          </Box>
          <Box bg='white' mb={4}  h={{base: 'fit-content', md: '433px'}} boxShadow='xl' borderRadius={8} w='fit-content' alignSelf='center' display='flex' flexDirection={{base: 'column-reverse', md: 'row'}} justifyContent='center' alignItems='start'>
            <ContactInfo />
            <ContactForm />
          </Box>
        </Box>
        <Footer />
      </Box>
    </>
  )
}

export default ContactPage