import { Box, Flex, Grid, GridItem } from '@chakra-ui/react'
import type { GetStaticProps, NextPage } from 'next'
import { AppProps } from 'next/app'
import Head from 'next/head'
import React from 'react'
import { useDispatch } from 'react-redux'
import CategoryNav from '../components/categoryNav'
import Featuring from '../components/featuring'
import Footer from '../components/footer'
import Header from '../components/header'
import ProductCardList from '../components/productCardList'
import Publicity from '../components/publicity'
import SearchBox from '../fragments/searchBox'
import { client } from '../services/contentful'
import { getProducts, setInitialData, setProducts } from '../store/Category'

type Props = {
  initialData: any
}
const Home = ({initialData}: Props) => {
  const dispatch = useDispatch()
  //setar configs apos pegar a data inicial
  React.useEffect(() => {
    dispatch(setProducts({items: initialData.items, total: initialData.total}))
    dispatch(setInitialData(initialData))
  }, [dispatch, initialData])

  return (
    <>
      <Head>
        <title>Comércios em Unamar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main" minH="100vh" maxW="100vw" display="flex" flexDirection="column" alignItems="center">
        <Header />
        <Flex flex="1" pt={6} flexDirection={{base: 'column', md:'row'}}  w="90%" alignItems="center" justifyContent='space-between'>
          <Box w='100%' p={4}>
            <Featuring />
            {/*<SearchBox />*/}
          </Box >
          <Box>
            <Publicity />
          </Box >
        </Flex>
        <Box w='90%'>
          <CategoryNav />
          <ProductCardList data={initialData}/>
        </Box>
        <Footer />
      </Box>
      
    </>
  )
}
export const getStaticProps: GetStaticProps = async () => {
  const initialData = await client.getEntries({content_type: 'barberin', 'limit': 12})
  return {
    props: { initialData },
  }
}

export default Home
