import { Box, Container, Grid, GridItem } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import CategoryNav from '../components/categoryNav'
import Featuring from '../components/featuring'
import Footer from '../components/footer'
import Header from '../components/header'
import ProductCardList from '../components/productCardList'
import Publicity from '../components/publicity'
import SearchBox from '../fragments/searchBox'
import { client } from '../services/contentful'

const Home: NextPage = () => {
  React.useEffect(() => {
    const getIt = async () => {
      const conteudo = await client.getEntries({'metadata.tags.sys.id[in]': 'pet'})
      console.log(conteudo.items)
    }
    getIt()
  }, [])
  return (
    <>
      <Head>
        <title>Comércio Unamar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main" minH="100vh" w="100vw" display="flex" flexDirection="column" alignItems="center">
        <Header />
        <Grid templateColumns='5fr 2fr' gap={6} flex="1"  w="90vw">
          <GridItem py={6} colStart={0} colEnd={2} minW="400px"  >
            <Featuring />
            <SearchBox />
            <CategoryNav />
            <ProductCardList />
          </GridItem >
          <GridItem py={6} colStart={2} colEnd={3} >
            <Publicity />
          </GridItem >
        </Grid>
        <Footer />
      </Box>
    </>
  )
}

export default Home
