import { Box, Container, Grid, GridItem } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import CategoryNav from '../components/categoryNav'
import Featuring from '../components/featuring'
import Footer from '../components/footer'
import Header from '../components/header'
import ProductCardList from '../components/productCardList'
import Publicity from '../components/publicity'
import SearchBox from '../fragments/searchBox'
import { client } from '../services/contentful'

const Home: NextPage = () => {
  React.useEffect(() => {
    const getIt = async () => {
      const conteudo = await client.getEntries({'metadata.tags.sys.id[in]': 'pet'})
      console.log(conteudo.items)
    }
    getIt()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main">
        <Header />
        <Featuring />
        <Grid maxW="auto" px={6} templateColumns='4fr 1fr' gap={6} >
          <GridItem >
            <SearchBox />
            <CategoryNav />
            <ProductCardList />
          </GridItem >
          <GridItem >
            <Publicity />
          </GridItem >
        </Grid>
        <Footer />
      </Box>
    </>
  )
}

export default Home
