import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { client } from '../services/contentful'

const Home: NextPage = () => {
  React.useEffect(() => {
    const getIt = async () => {
      const conteudo = await client.getEntries({'metadata.tags.sys.id[in]': 'pet'})
      console.log(conteudo.items)
    }
    getIt()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        
      </main>
    </>
  )
}

export default Home
